[package]
name = "lorentz-dev/fastapi"
version = "0.1.1"

[dependencies]
"wasmer/python-native" = "=0.1.3"

[fs]
"/app" = "./src"
"/cpython/lib/python3.13/site-packages" = "./wasix-site-packages"

[[command]]
name = "script"
module = "wasmer/python-native:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/app/main.py"]
env = ["PYTHONEXECUTABLE=/bin/python", "PYTHONHOME=/cpython", "HOME=/app"]
